# Generated by Django 4.2.4 on 2023-09-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Business', 'Business'), ('Science', 'Science'), ('Health', 'Health'), ('Latest', 'Latest'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Sports', 'Sports')], max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='articles/images')),
                ('rating', models.CharField(choices=[('4', '4'), ('2', '2'), ('1', '1'), ('0', '0'), ('3', '3')], max_length=10)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categorymodel')),
            ],
        ),
    ]
