# Generated by Django 4.2.4 on 2023-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('1', '1'), ('0', '0'), ('3', '3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Latest', 'Latest'), ('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Science', 'Science'), ('Entertainment', 'Entertainment'), ('Health', 'Health')], max_length=20),
        ),
    ]
