# Generated by Django 4.2.4 on 2023-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlemodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('1', '1'), ('0', '0')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Latest', 'Latest'), ('Science', 'Science'), ('Sports', 'Sports'), ('Business', 'Business'), ('Health', 'Health'), ('Entertainment', 'Entertainment')], max_length=20),
        ),
    ]
