# Generated by Django 4.2.4 on 2023-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articlemodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('1', '1'), ('3', '3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Business', 'Business'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Science', 'Science'), ('Technology', 'Technology'), ('Latest', 'Latest'), ('Sports', 'Sports')], max_length=20),
        ),
    ]
