# Generated by Django 4.2.4 on 2023-09-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlemodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.categorymodel'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('2', '2'), ('1', '1'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Latest', 'Latest'), ('Business', 'Business'), ('Science', 'Science'), ('Health', 'Health'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment')], max_length=20),
        ),
    ]
