# Generated by Django 4.2.4 on 2023-09-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articlemodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Health', 'Health'), ('Science', 'Science'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Latest', 'Latest'), ('Technology', 'Technology'), ('Business', 'Business')], max_length=20),
        ),
    ]
